on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events on master branch
      - master
      # Push events to branches matching refs/heads/mona/octocat
      - "mona/octocat"
      # Push events to branches matching refs/heads/releases/10
      - "releases/**"
    # Sequence of patterns matched against refs/tags
    tags:
      - v1 # Push events to v1 tag
      - v1.* # Push events to v1.0, v1.1, and v1.9 tags
jobs:
  hello_github_actions:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
  # deploy_to_firebase:
  #   - name: GitHub Action for Firebase
  #     uses: w9jds/firebase-action@v1.4.0
